---
title: "Untitled"
output: html_document
date: "2025-11-06"
---


## Tax

```{r pressure, echo=FALSE}

library(rpart)

car_data <- read.csv("bmw.csv")

summary(car_data)

plot(car_data$price, car_data$tax, main = "Car Price vs Tax", xlab="Price", ylab="Tax")

boxplot(tax ~ price, data = car_data, main = "Tax by Price",
        xlab = "Tax", ylab="Price") 

carModel <- rpart(tax ~ price, data = car_data)
summary(carModel)

```

```{r}
summary(car_data$tax)
hist(car_data$tax, main = "Distribution of Car Tax", xlab = "Tax", col = "blue",border = "white")
boxplot(car_data$tax, data = car_data, main = "Tax", xlab = "Tax")
carModel <- rpart(tax ~ fuelType, data = car_data)
summary(carModel)

```
// After running this rpart we discover something important 
   Avg tax for electric/hybrid: 79
   Avg tax for pretrol/diesal: 120

## Price

```{r}
summary(car_data$price)
hist(car_data$price, main = "Distribution of Car Price", xlab = "Price", col = "blue",border = "white")
boxplot(car_data$price, data = car_data, main = "Distibution of Car Price", xlab = "Price")
plot(car_data$price, car_data$engineSize, main = "Car Price vs Engine Size", xlab="Price", ylab="Engine")
carModel <- rpart(price ~ engineSize, data = car_data)
summary(carModel)
```
//after running rpart it seems that the bigger the engine size,     the higher the price with a split between 1.95, 2.9, and 4,2      liters. 
  For engines < 1.95 avg price: 16,726
  For engines 1.95-2.9 avg price: 20,651
  For engines 2.9-4.2 avg prices: 31,475
  For engines > 4.2 avg prices: 46,536




